### ISSUE TITLE
Configuração do arquivo docker-compose

### ISSUE THREAD

**Issue by geovani-brito** [Grupo-Tres/app-backend#6]
Por enquanto, o container com o Postgres está sendo iniciado manualmente. Será necessário criar um arquivo de configuração `docker-compose.yaml` para poder iniciar o banco automaticamente ao rodar o comando pelo `npm`. 

Já tentei criar um arquivo com essas configurações:
``` yaml
version: "2.4"
services:
  postgres_dev:
    container_name: "corleone"
    image: "postgres:13.3-alpine"
    env_file:
      - .env
    ports:
      - "54320:5432"
    volumes:
      - postgres_data:/data/postgres
    restart: unless-stopped
volumes:
  postgres_data:
```
E esse comando no `package.json`:
`docker-compose -f infra/docker-compose.development.yml up -d`
mas por algum motivo não funcionou.
